# Wrangler configuration for Spark Web Edge backend API
name = "sparkweb-api"
main = "worker.js"
compatibility_date = "2024-03-01"

# Bind D1 Database instance to the Worker
[[d1_databases]]
binding = "DB"
database_name = "sparkweb-db"
database_id = "8341b44f-6cb8-40b7-ade0-5b227ea7d76e"
